name: counter
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  #imagens e arquivos de recursos são configurados desta forma
  assets:
    - lib/assets/
    - lib/assets/il8n/ 
    - lib/assets/images/

  fonts:
    - family: Lora
      fonts:
        - asset: lib/assets/fonts/Lora-Regular.ttf
        - asset: lib/assets/fonts/Lora-Bold.ttf
          weight: 400
        - asset: lib/assets/fonts/Lora-Italic-VariableFont_wght.ttf
          style: italic
    - family: ZillaSlab
      fonts:
        - asset: lib/assets/fonts/ZillaSlab-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/ZillaSlab-Bold.ttf
          weight: 400
        - asset: lib/assets/fonts/ZillaSlab-LightItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/ZillaSlab-Medium.ttf
          weight: 700
    - family: Nunito
      fonts:
        - asset: lib/assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Nunito-SemiBoldItalic.ttf
          weight: 800
          style: italic
        - asset: lib/assets/fonts/Nunito-BlackItalic.ttf
          weight: 900
          style: italic